# Generated by Django 5.2.7 on 2025-11-11 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assigned_nurse',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
